DROP DATABASE netflix;
CREATE DATABASE netflix;
use netflix;

CREATE TABLE IF NOT EXISTS `CATEGORIES`
(
  `ID`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `NAME`        VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `unique` (`NAME` ASC)
);

CREATE TABLE IF NOT EXISTS `TV_SHOWS`
(
  `ID`          	BIGINT(20)    NOT NULL AUTO_INCREMENT,
  `NAME` 			VARCHAR(256)  NOT NULL,
  `SHORT_DESC` 		VARCHAR(256)  NULL DEFAULT NULL,
  `LONG_DESC` 		VARCHAR(2048) NULL DEFAULT NULL,
  `YEAR` 			YEAR(4) 	  NOT NULL,
  `RECOMMENDED_AGE` TINYINT 	  NOT NULL,
  `ADVERTISING` 	VARCHAR(256)  NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
 
);

CREATE TABLE IF NOT EXISTS `SEASONS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NUMBER` 		TINYINT 	 NOT NULL,
  `NAME` 		VARCHAR(256) NOT NULL,
  `TV_SHOW_ID`  BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_SEASONS_TV_SHOW_ID`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES `TV_SHOWS` (ID)
);

CREATE TABLE IF NOT EXISTS `CHAPTERS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NUMBER` 		TINYINT 	 NOT NULL,
  `NAME` 		VARCHAR(256) NOT NULL,
  `DURATION` 	TINYINT 	 NOT NULL,
  `SEASON_ID`  BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CHAPTERS_SEASON_ID`
    FOREIGN KEY (SEASON_ID) REFERENCES `SEASONS` (ID)
);






CREATE TABLE tvshows_categories(
ID_TV_SHOW bigint(20) REFERENCES tv_shows(ID), 
ID_CATEGORY bigint(20) REFERENCES categories(ID), 

PRIMARY KEY(ID_TV_SHOW, ID_CATEGORY) );



CREATE TABLE ACTORS (
	ID 			BIGINT(20)		NOT NULL AUTO_INCREMENT,
	NAME 		VARCHAR(256) 	NOT NULL,
	LAST_NAME 	VARCHAR(256)	NOT NULL,
    AGE			BIGINT(20)		NOT NULL,
    NATIONALITY varchar(20)		NOT NULL,
	 PRIMARY KEY (`ID`)


);



CREATE TABLE actors_chapters(ID_ACTOR bigint(20) REFERENCES actors(ID), ID_CHAPTER bigint(20) REFERENCES chapters(ID), PRIMARY KEY(ID_ACTOR, ID_CHAPTER)	);



CREATE TABLE AWARD (ID BIGINT(20) NOT NULL AUTO_INCREMENT, NAME VARCHAR(256) NOT NULL, ID_TVSHOW BIGINT(20) REFERENCES tv_shows(ID),PRIMARY KEY(ID));